name: sweb-backend-dev

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  TEST:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: run Unittest
        run: python -m unittest discover tests/

  PUBLISH:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Publish to Docker registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: registry.datexis.com/ksachs/sweb-backend-dev:latest
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSPHRASE }}
          registry: registry.datexis.com
          snapshot: true
      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
      - name: Restart sweb-dev pod
        run: kubectl -n sachs delete pod -l app=sweb-backend-dev
